Repository CS3219-AY2223S1/cs3219-project-ay2223s1-g48, pull requests merged in 2022-10, with the labels that each got.

#24 Question service
  .gitignore
  question-service/controller/question-controller.js
  question-service/index.js
  question-service/model/question-model.js
  question-service/model/question-orm.js
  question-service/model/repository.js
  question-service/package-lock.json
  question-service/package.json
Labels: enhancement

#29 Bug fixes 25 26 27 fr 28
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MatchingPage.js
  frontend/src/components/MatchingRoom.js
  frontend/src/components/Navbar.js
  frontend/src/index.css
  user-service/package-lock.json
Labels: bug, enhancement

#30 Question service v2
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/QuestionCreate.js
  frontend/src/components/QuestionList.js
  frontend/src/components/QuestionPage.js
  frontend/src/components/QuestionUpdate.js
  frontend/src/configs.js
  frontend/src/index.css
  question-service/controller/question-controller.js
  question-service/index.js
  question-service/model/question-model.js
  question-service/model/question-orm.js
  question-service/model/repository.js
  question-service/package-lock.json
  question-service/package.json
Labels: enhancement

#31 Communication Service + Matching Room (frontend) + Matching Service
  .gitignore
  communication-service/index.js
  communication-service/package-lock.json
  communication-service/package.json
  frontend/src/App.js
  frontend/src/Images/Background.jpg
  frontend/src/Images/icons.svg
  frontend/src/Images/logo.svg
  frontend/src/components/AppError.js
  frontend/src/components/LandingPage.js
  frontend/src/components/LoginPage.js
  frontend/src/components/MatchingPage.js
  frontend/src/components/MatchingRoom.js
  frontend/src/components/SignupPage.js
  frontend/src/constants.js
  frontend/src/index.css
  frontend/src/index.js
  matching-service/index.js
  matching-service/matching-service-configs.js
  matching-service/matching-service-constants.js
  matching-service/package-lock.json
  matching-service/package.json
  question-service/package-lock.json
Labels: enhancement

#33 Updates and Bug fixes caa 21/10/2022
  communication-service/index.js
  frontend/package-lock.json
  frontend/src/components/MatchingPage.js
  frontend/src/components/MatchingRoom.js
  matching-service/index.js
  package-lock.json
Labels: bug, enhancement

#34 Fix bugs for question service frontend
  frontend/src/components/QuestionCreate.js
  frontend/src/components/QuestionList.js
  frontend/src/components/QuestionUpdate.js
Labels: bug

#36 bugfix for update and patch user password
  user-service/model/repository.js
  user-service/model/user-orm.js
Labels: bug

#38 implements regex for checking email format
  user-service/controller/user-controller.js
  user-service/model/repository.js
  user-service/model/user-orm.js
Labels: bug, enhancement

#37 UI improvement -- Part I
  frontend/package-lock.json
  frontend/package.json
  frontend/src/.env
  frontend/src/App.js
  frontend/src/Images/easy_1.png
  frontend/src/Images/hard_1.png
  frontend/src/Images/medium_1.png
  frontend/src/Images/medium_2.png
  frontend/src/Images/tick_1.png
  frontend/src/Images/tick_2.png
  frontend/src/components/Dropdown.js
  frontend/src/components/Editor.js
  frontend/src/components/FindPage.js
  frontend/src/components/LoginPage.js
  frontend/src/components/MatchingPage.js
  frontend/src/components/MatchingRoom.js
  frontend/src/components/Navbar.js
  frontend/src/components/Navitem.js
  frontend/src/components/SignupPage.js
  frontend/src/index.css
  user-service/controller/user-controller.js
  user-service/model/repository.js
  user-service/model/user-model.js
  user-service/model/user-orm.js
Labels: enhancement

#40 Dockerize peerprep
  .dockerignore
  communication-service/.dockerignore
  communication-service/Dockerfile
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  matching-service/.dockerignore
  matching-service/.env
  matching-service/Dockerfile
  matching-service/matching-service-configs.js
  matching-service/package-lock.json
  matching-service/package.json
  question-service/.dockerignore
  question-service/Dockerfile
  user-service/.dockerignore
  user-service/Dockerfile
Labels: enhancement
